### PR TITLE
Wrangling Data A

### PR DESCRIPTION
**Pull request by BeccaGill**

### CODE REVIEW

**Comment by davidkane9** [comment]
This is causing an error in the checks

Probable cause is tools tutorial not looking like other tutorial

Note the directory structure they all use

Note they are always tutorial.Rmd

And so on

**Comment by BeccaGill** [comment]
Hi Preceptor,

Tools tutorial is not finished. I only meant to create a pull request for
the edits I made on tutorial-2. Sorry about that.

**Comment by davidkane9** [comment]
No worries. I will close this PR. You can then make another with just those changes.

**Comment by BeccaGill** [comment]
Hi again,

I know it is late, and I am sorry for reaching out at this hour. I have my
comments all ready and tools tutorial finished. There are a few coding
questions/errors I was hoping we could go over tomorrow before I submit the
PR. Would it be okay to  go over it quickly during our meeting?

Best,
Becca

**Pull request closed without merging**
