### PR TITLE
Adding R CMD check and build badge

### PR DESCRIPTION
**Pull request by itsyaoyu**

### CODE REVIEW

**Comment by davidkane9** [comment]
Note the failing checks. I will still accept the PR. Can you submit a do-nothing PR to see if the checks start working?

**Comment by itsyaoyu** [comment]
No need - it's running on push as well. I think it might be failing b/c of unfinished parts in tutorial.Rmd? At least that's what seems to be failing from the logs.

**Comment by davidkane9** [comment]
R CMD check works locally with no problem.

Current Github Actions check seems to fail even before we get to running R CMD check. Can't even install the OS?

https://github.com/davidkane9/PPBDS.data/actions/runs/212980337

**Comment by itsyaoyu** [comment]
Ah, the check runs on the most popular OS types. If you look into the logs, you can see `0 errors v | 1 warning x | 4 notes x`

**Comment by itsyaoyu** [comment]
It seems like there some warning is  `'::' or ':::' import not declared from: 'rmarkdown'` and the notes are just some suggestions.

**Comment by davidkane9** [comment]
I have no problem with the Notes, but there should not be any warnings.
This is what I see locally:

==> roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))
Loading PPBDS.dataWriting NAMESPACE
Writing NAMESPACE
Documentation completed
==> R CMD build --no-manual PPBDS.data
* checking for file ‘PPBDS.data/DESCRIPTION’ ... OK
* preparing ‘PPBDS.data’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘PPBDS.data_0.3.2.9000.tar.gz’
==> R CMD check --no-manual PPBDS.data_0.3.2.9000.tar.gz
* using log directory ‘/Users/davidkane/Desktop/projects/PPBDS.data.Rcheck’
* using R version 4.0.2 (2020-06-22)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* using option ‘--no-manual’
* checking for file ‘PPBDS.data/DESCRIPTION’ ... OK
* this is package ‘PPBDS.data’ version ‘0.3.2.9000’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘PPBDS.data’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 15.6Mb
  sub-directories of 1Mb or more:
    data        5.1Mb
    help        1.5Mb
    tutorials   9.0Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘dslabs’ ‘fueleconomy’ ‘gapminder’ ‘ggthemes’ ‘gt’ ‘nycflights13’
  ‘skimr’ ‘tidyverse’ ‘viridis’
  All declared Imports should be used.
Unexported objects imported by ':::' calls:
  ‘learnr:::get_all_state_objects’
  ‘learnr:::submissions_from_state_objects’
  See the note in ?`:::` about the use of this operator.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... NOTE
  Note: found 217 marked UTF-8 strings
* checking data for ASCII and uncompressed saves ... OK
* checking examples ... NONE
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* DONE
Status: 3 NOTEs

See
  ‘/Users/davidkane/Desktop/projects/PPBDS.data.Rcheck/00check.log’
for details.


R CMD check succeeded

**Comment by itsyaoyu** [comment]
Interesting - I'll have to look into it.

**Pull request merged**
