### PR TITLE
edits and merge fixes 

### PR DESCRIPTION
**Pull request by BeccaGill**

### CODE REVIEW

**Comment by davidkane9** [comment]
Did you do a pr_pull_upstream()? I deleted 4 or 5 questions from tutorial 4 which you have now added back.

**Comment by BeccaGill** [comment]
Yes I pulled. I am sorry. I did not realize I added back those questions.

**Comment by BeccaGill** [comment]
Do you think I should do the set up once again and create a new branch?

**Comment by davidkane9** [comment]
Yeah!

**Pull request closed without merging**
