### PR TITLE
Vis. 1A comment changes

### PR DESCRIPTION
**Pull request by BeccaGill**

### CODE REVIEW

**Comment by davidkane9** [comment]
Need to fix the merge conflict first

**Comment by BeccaGill** [comment]
I can’t find any of the “HEAD” or ">>>” to indicate there is a conflict in the Vis 1A file.

**Comment by davidkane9** [comment]
Your  pull request includes a bunch of other files.

**Comment by davidkane9** [comment]
Nice job

**Comment by BeccaGill** [comment]
Hello-
The commits I am making and pushing are not showing up in my Git Hub account. There are no messages saying my branch is behind. 
Do you know the reason for this?

Best,
Becca

**Pull request merged**
