### PR TITLE
Instructions.Rmd edits 

### PR DESCRIPTION
**Pull request by BeccaGill**

### CODE REVIEW

**Comment by davidkane9** [comment]
Leave the Horst stuff at the end on a Miscelaneous section, or whatever. Don't want to forget that.

**Comment by BeccaGill** [comment]
What Horst stuff are you referring to?

**Comment by davidkane9** [comment]
This and following:

### Suggestions from Allison Horst
The main question was: How do we incorporate tutorial questions directly into the chapter itself? Allison is the world expert on this topic. 
* She is concerned about user loads for published Shiny apps - would recommend that we use the basic or higher plan.

**Comment by BeccaGill** [comment]
Great, thank you!

**Comment by davidkane9** [comment]
Good stuff!

**Pull request merged**
